export const CartTypes = {
    SET_HIDDEN_STATE: 'SET_HIDDEN_STATE',
    ADD_CART_ITEM: 'ADD_CART_ITEM',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
    DECREASE_CART_ITEM: 'DECREASE_CART_ITEM',
};